CREATE TABLE IF NOT EXISTS stock_watchlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market VARCHAR(20) NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    rank_no INT NOT NULL,
    source VARCHAR(30) NOT NULL,
    base_date DATE NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_stock_watchlist_market_symbol UNIQUE (market, symbol)
);

DELETE FROM stock_watchlist
WHERE market = 'US'
  AND source = 'SEED_US_MARKET_CAP';

INSERT INTO stock_watchlist (market, symbol, name, rank_no, source, base_date, enabled)
VALUES
    ('US', 'NVDA', 'NVIDIA Corporation', 1, 'SEED_US_MARKET_CAP', DATE '2026-05-01', TRUE),
    ('US', 'GOOGL', 'Alphabet Inc.', 2, 'SEED_US_MARKET_CAP', DATE '2026-05-01', TRUE),
    ('US', 'AAPL', 'Apple Inc.', 3, 'SEED_US_MARKET_CAP', DATE '2026-05-01', TRUE),
    ('US', 'MSFT', 'Microsoft Corporation', 4, 'SEED_US_MARKET_CAP', DATE '2026-05-01', TRUE),
    ('US', 'AMZN', 'Amazon.com, Inc.', 5, 'SEED_US_MARKET_CAP', DATE '2026-05-01', TRUE),
    ('US', 'AVGO', 'Broadcom Inc.', 6, 'SEED_US_MARKET_CAP', DATE '2026-05-01', TRUE),
    ('US', 'TSM', 'Taiwan Semiconductor Manufacturing Company Limited', 7, 'SEED_US_MARKET_CAP', DATE '2026-05-01', TRUE),
    ('US', 'META', 'Meta Platforms, Inc.', 8, 'SEED_US_MARKET_CAP', DATE '2026-05-01', TRUE),
    ('US', 'TSLA', 'Tesla, Inc.', 9, 'SEED_US_MARKET_CAP', DATE '2026-05-01', TRUE),
    ('US', 'BRK.B', 'Berkshire Hathaway Inc.', 10, 'SEED_US_MARKET_CAP', DATE '2026-05-01', TRUE);
